Planet-Planet interaction
TechnicJelle/SolarSystem pull request #29
Opened 2021-04-19 19:48 UTC by EV4gamer

Added planet-planet interaction
Updated the attractMass function to also work between two planets, and not only a planet and a sun
Explode() can now also take a arraylist as input, which will be used in the future for planet collisions/destruction

2021-04-19 19:51 UTC, EV4g commented
There are still things which need to be added, but planet-planet interactions work.
A repelling force should be added, so planets dont clutter and destroy the universe.

2021-04-20 21:09 UTC, EV4gamer commented
Latest version is a stable version

2021-04-20 22:02 UTC, TechnicJelle commented on Planet.pde
> +  boolean explode_me;
Please rename this variable to `explodeMe`, to comply with the naming style of the rest of the variables.

Please also move the ` = false` out of the constructor into the raw class

2021-04-20 22:03 UTC, TechnicJelle commented on SolarSystem.pde
> +      for (int i = planets.size() - 1; i >= 0; i--) {
Some trailing spaces

2021-04-20 22:04 UTC, TechnicJelle commented on SolarSystem.pde
> +  if (d > p.radius + o.radius) {
Trailing spaces

2021-04-20 22:04 UTC, TechnicJelle commented on SolarSystem.pde
> +          explode(p, i, planets);
Feels redundant. `planets` is a global variable

2021-04-20 22:04 UTC, TechnicJelle commented on Planet.pde
> +
Trailing spaces

2021-04-20 22:05 UTC, TechnicJelle commented on SolarSystem.pde
> +        }
Trailing spaces

2021-04-20 22:05 UTC, TechnicJelle commented on SolarSystem.pde
> +            if (z != i && dist(p.pos, planets.get(z).pos) < (p.radius + planets.get(z).radius) / 2 && degrees(PVector.angleBetween(planets.get(z).vel, p.vel)) > 10 && p.mass < 10 * planets.get(z).mas
Trailing spaces

2021-04-20 22:06 UTC, TechnicJelle commented on SolarSystem.pde
> +boolean roche(Planet p, Planet M) {
Trailing spaces

2021-04-20 22:06 UTC, TechnicJelle requested changes
Some style changes, but the rest is looking good!

2021-04-20 22:19 UTC, EV4gamer commented
Changes have been made

2021-04-20 22:51 UTC, TechnicJelle approved these changes

2021-04-20 22:51 UTC, merged